CREATE DATABASE SQLTUTOR;

ALTER DATABASE SQLTUTOR MODIFY NAME = SQLTUTORIAL;

SP_RENAMEDB SQLTUTORIAL, SQLTUTOR;

DROP DATABASE SQLTUTOR;

ALTER DATABASE SQLTUTOR SET SINGLE_USER WITH ROLLBACK IMMEDIATE;